/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.weather

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = App()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
